### ISSUE TITLE
How to generate inline include SourceMap

### ISSUE THREAD

**Issue by steelbrain** [lydell/source-map-concat#1]
Your package demonstrates sourcemap creation by appending it at the end of the last file, but how does one create sourcemaps when he does something like

``` js
(function(){
// @Compiler-Include "First.js"
// @Compiler-Include "Second.js"
})()
```

and the output is 

``` js
(function(){
class A{}
class B{}
})()
```

**Comment by lydell** [comment]
I don’t get it.

**Comment by steelbrain** [comment]
I mean, the input is in the first block, the output is in the second block, the script is https://github.com/steelbrain/UCompiler
Because You are experienced with sourcemaps, I wanted to ask you how can one generate sourcemaps for an include like this. I hope it's clear enough this time :D
